table DimPromotion
	lineageTag: ac46eae3-5c32-4782-b9c2-ac0a84ee755b

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: abd76d5f-3bde-44dc-bf9b-f97d20d52d2e
		summarizeBy: none
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column PromotionLabel
		dataType: string
		lineageTag: 8678a3a2-69a7-4c9a-bef6-3f009fc0fc56
		summarizeBy: none
		sourceColumn: PromotionLabel

		annotation SummarizationSetBy = Automatic

	column PromotionName
		dataType: string
		lineageTag: b0884ce1-5546-4af4-b364-2c32780f78fb
		summarizeBy: none
		sourceColumn: PromotionName

		annotation SummarizationSetBy = Automatic

	column DiscountPercent
		dataType: double
		lineageTag: 89d9271e-4a00-466f-88a6-6dc90bdbe507
		summarizeBy: sum
		sourceColumn: DiscountPercent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StartDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: eb5a09a0-3c91-4873-8416-abc73a0d56a3
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: ed4cce07-7b20-4863-aec6-26995670e870
			defaultHierarchy: LocalDateTable_072802ae-85f2-4c23-9b1e-18efde540a30.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5509c35c-22f0-4747-9bab-e62b86e8bde3
		summarizeBy: none
		sourceColumn: EndDate

		variation Variation
			isDefault
			relationship: 2ffb8680-4186-46a6-aeb7-5b8a7e9a78a7
			defaultHierarchy: LocalDateTable_4aa8b58a-015b-4d73-ae1c-ec2b7acadeb7.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DayDifferences = DATEDIFF(DimPromotion[StartDate],DimPromotion[EndDate],DAY)
		formatString: 0
		lineageTag: d46bb805-5db0-4bc0-a413-2cde98d3905a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition DimPromotion = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\jrodriji\OneDrive - NTT DATA EMEAL\Learning\Power BI\Excels Proyectos\Proyecto 5 - DAX\ContosoSales.accdb"), [CreateNavigationProperties=true]),
				    _DimPromotion = Source{[Schema="",Item="DimPromotion"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(_DimPromotion,{"PromotionKey", "PromotionLabel", "PromotionName", "DiscountPercent", "StartDate", "EndDate"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

