table DimStores
	lineageTag: 2a75075c-969d-48b7-8422-6a7706047b08

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: bb22cb96-ab42-46e5-a7ba-e4ec08d458c7
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: double
		isHidden
		lineageTag: 3e26faee-3964-497e-8ec9-1fff72df93be
		summarizeBy: none
		sourceColumn: GeographyKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StoreType
		dataType: string
		lineageTag: b7cf859a-bc93-46ae-8b4b-64419b2c1323
		summarizeBy: none
		sourceColumn: StoreType

		annotation SummarizationSetBy = Automatic

	column StoreName
		dataType: string
		lineageTag: c49a3d64-dca0-4543-a626-c3ff54054909
		summarizeBy: none
		sourceColumn: StoreName

		annotation SummarizationSetBy = Automatic

	column EmployeeCount
		dataType: double
		lineageTag: 29173c9e-c071-4932-984e-b022d28c1dd0
		summarizeBy: none
		sourceColumn: EmployeeCount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SellingAreaSize
		dataType: double
		lineageTag: 05a0f690-7391-47e7-bf05-661261edd3c8
		summarizeBy: none
		sourceColumn: SellingAreaSize

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Store Measurement' =
			
			SUBSTITUTE(DimStores[StoreName],"Store", BLANK())
		lineageTag: 60b6dec1-a146-455e-914c-2d23982802ca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Physical Location' =
			
			DimStores[Store]&", "&DimStores[RegionCountryName]&", "&DimStores[ContinentName]
		lineageTag: 294dbbc9-ddae-45f5-8085-b15290f4507a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Store
		dataType: string
		lineageTag: c1c3029a-229a-41b3-8084-e96f997b3bbb
		summarizeBy: none
		sourceColumn: Store

		annotation SummarizationSetBy = Automatic

	column ContinentName
		dataType: string
		lineageTag: 9ecad651-40ff-4356-8fb7-76d0f105cde5
		summarizeBy: none
		sourceColumn: ContinentName

		annotation SummarizationSetBy = Automatic

	column RegionCountryName
		dataType: string
		lineageTag: 0fbcd22b-edb1-452c-ac68-0ef1d734eb42
		dataCategory: Continent
		summarizeBy: none
		sourceColumn: RegionCountryName

		annotation SummarizationSetBy = Automatic

	column 'Store Size' =
			
			SWITCH(
			    TRUE(),
			    DimStores[SellingAreaSize]<=500,
			    "Pequeña",
			    DimStores[SellingAreaSize]<=800,
			    "Mediana",
			    DimStores[SellingAreaSize]>800,
			    "Grande"
			)
		lineageTag: 94462e77-91cd-41ae-80e5-af3da37b485e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DimStores = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\jrodriji\OneDrive - NTT DATA EMEAL\Learning\Power BI\Excels Proyectos\Proyecto 5 - DAX\ContosoSales.accdb"), [CreateNavigationProperties=true]),
				    _DimStores = Source{[Schema="",Item="DimStores"]}[Data],
				    #"Inserted Text Between Delimiters" = Table.AddColumn(_DimStores, "Text Between Delimiters", each Text.BetweenDelimiters([StoreName], "Contoso ", " Store"), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Between Delimiters",{{"Text Between Delimiters", "Store"}}),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Renamed Columns", {{"Store", each Text.BeforeDelimiter(_, " No."), type text}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Extracted Text Before Delimiter",{"StoreKey", "GeographyKey", "StoreType", "StoreName", "EmployeeCount", "SellingAreaSize", "Store"}),
				    #"Merged Queries" = Table.NestedJoin(#"Reordered Columns", {"GeographyKey"}, DimGeography, {"GeographyKey"}, "DimGeography", JoinKind.LeftOuter),
				    #"Expanded DimGeography" = Table.ExpandTableColumn(#"Merged Queries", "DimGeography", {"ContinentName", "RegionCountryName"}, {"ContinentName", "RegionCountryName"})
				in
				    #"Expanded DimGeography"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

