table FactSales
	lineageTag: f1b30b8e-1f6d-4b75-8b89-c10aadda08ab

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: 0664d66c-55f4-4ba8-b6be-92db5cb1f760
		summarizeBy: count
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 1e67aff3-4a70-4aaf-8f4c-30824e43a88a
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ChannelKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ca609906-1ba8-4b5e-90dd-179d6e78af34
		summarizeBy: none
		sourceColumn: ChannelKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8af6bba4-2652-4cb4-989d-2c796cf21197
		summarizeBy: none
		sourceColumn: StoreKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 68aef41b-fc0a-4ded-8483-137a79db0a09
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7f8275b5-89c5-4946-add8-0813a9f40cb4
		summarizeBy: none
		sourceColumn: PromotionKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesQuantity
		dataType: int64
		formatString: 0
		lineageTag: f59ef046-b259-4c48-9657-6ab164d637e6
		summarizeBy: sum
		sourceColumn: SalesQuantity

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: 9e4e0fd0-3e45-4aa4-928c-c84ea3070638
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	column Devolution =
			
			IF(NOT FactSales[ReturnQuantity]=0, "Si","No")
		lineageTag: 672167ae-bc5a-4cfe-88ef-222f92fb735c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Type de Sale' =
			
			IF(FactSales[SalesQuantity]>10,
			"Mayoreo",
			"Menuedeo"
			)
		lineageTag: b884327c-273b-468b-b901-6bbb3e9eb837
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Type Devolution' =
			
			IF(FactSales[ReturnQuantity] = 0,
			BLANK(),
			    IF(FactSales[ReturnQuantity] = 1,
			    "Unica",
			    "Multiple")
			)
		lineageTag: 983c65d4-80fd-4b45-bc41-c664ab9427e0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Wholesale Discount' =
			
			1 - IF(FactSales[Type de Sale] = "Mayoreo" && FactSales[ChannelKey] = 1 && FactSales[PromotionKey] = 1,
			    0.05,
			    0
			)
		formatString: 0%;-0%;0%
		lineageTag: e445d736-ca18-4407-b516-4e510e506f4c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition FactSales = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\jrodriji\OneDrive - NTT DATA EMEAL\Learning\Power BI\Excels Proyectos\Proyecto 5 - DAX\ContosoSales.accdb"), [CreateNavigationProperties=true]),
				    _FactSales = Source{[Schema="",Item="FactSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(_FactSales,{"OrderID", "DateKey", "channelKey", "StoreKey", "ProductKey", "PromotionKey", "SalesQuantity", "ReturnQuantity"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"DateKey", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"channelKey", "ChannelKey"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

