table 'Parameter UnitPrice'
	lineageTag: 80cf41fc-cf13-40ec-b006-02090488e640

	measure 'Parameter UnitPrice Value' = SELECTEDVALUE('Parameter UnitPrice'[Parameter UnitPrice])
		lineageTag: 8e4dbfe6-8be6-4dda-b93c-1409f51a6981

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Parameter UnitPrice'
		formatString: 0%;-0%;0%
		lineageTag: 7ad15b0d-685d-4ef6-91b1-0599ec1f2e9e
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Parameter UnitPrice' = calculated
		mode: import
		source = GENERATESERIES(-0.5, 0.5, 0.01)

	annotation PBI_Id = b1e4d3fc1f8b45bab1047832956d3c23

